### ISSUE TITLE
활동선택 창에 뒤로가기 버튼 클릭 시 이미지 뜨지 않음

### ISSUE THREAD

**Issue by 218dahye** [jin20415/eclipse_growstudent#4]
활동선택 창에 있는 뒤로가기 버튼을 누르면 집 이미지가 뜨지 않음.

**Comment by 218dahye** [comment]
집 이미지 패널을 하나 더 생성함.
하지만 활동하기 버튼을 누르면 활동선택 이미지 패널이 뜨지 않음

**Comment by jin20415** [comment]
홈 이미지 경로를 지정한 이미지 변수를 추가하여 활동선택 패널에서 뒤로가기를 눌렀을 때 홈 화면이 뜨도록 함.
